export const Href = "#javascript";
export const ImagePath = "/assets/images";
export const StarColor = "var(--theme-default)";
export const StarColorTwo = "#D77748";

//Layout
export const Loading: string = "Loading...";
export const Search: string = "Search ..";
export const NotiFications: string = "NotiFications";
export const NewDailyOfferAdded: string = "New daily offer added";
export const CheckAll: string = "Check all";
export const Bookmark: string = "Bookmark";
export const AddNewBookmark: string = "Add New Bookmark";
export const Back: string = "Back";
export const Messages: string = "Messages";
export const Cart: string = "Cart";
export const OrderTotal: string = "Order Total";
export const GoToYourCart: string = "Go to your cart";
export const Checkout: string = "Checkout";
export const Pinned: string = "Pinned";
export const ErrorMessage = 'Ops!! There are no result found.';

//Ui Kits- Modal
export const Modal: string = "Modal";
export const BasicModal: string = "Basic Modal";
export const Simple: string = "Simple";
export const ScrollingContent: string = "Scrolling content";
export const UXDesigners: string = "UX Designer ";
export const WebDesigns: string = "Web Design ";
export const WebDesigner: string = "Web Designer ";
export const ButtonSmall: string = "button";
export const TooltipsAndPopovers: string = "Tooltips and popovers";
export const PopoverModal: string = "Popover in a modal";
export const TooltipsModal: string = "Tooltips in a modal";
export const OpenModalForMofi: string = "Open modal for Mofi";
export const SizesModal: string = "Sizes Modal";
export const FullScreenModals: string = "Full Screen Modal";
export const ExtraLargeModals: string = "Extra large Modal";
export const LargeModals: string = "Large Modal";
export const SmallModals: string = "Small Modal";
export const FullScreenModal: string = "Fullscreen Modal";
export const FullScreenBelowSM: string = "Full Screen Below sm";
export const FullScreenBelowMD: string = "Full Screen Below md";
export const FullScreenBelowLG: string = "Full Screen Below lg";
export const FullScreenBelowXL: string = "Full Screen Below xl";
export const FullScreenBelowXXL: string = "Full Screen Below xxl";
export const CenteredModals: string = "Centered Modal ";
export const VerticallyCentered: string = "Vertically centered";
export const ToggleBetweenModal: string = "Toggle Between Modals ";
export const OpenFirstModal: string = "Open first Modal ";
export const StaticBackdropModals: string = "Static Backdrop Modal";
export const MofiCustomModal: string = "Mofi Custom Modals ";
export const BalanceAmount: string = "$768,987.90";
export const Cancel: string = "Cancel";
export const Save: string = "Save";
export const Close: string = "Close";
export const SaveChanges: string = "Save changes";
export const ClickOut: string = "Click Out";
export const MofiSignUp: string = "Mofi SIGN-UP";
export const MofiLogin: string = "Mofi Login";
export const StaticBackdropModalBtn: string = "Static backdrop modal";
export const SomethingWentWrong: string = "Ohh! Something went wrong!";
export const AlreadyLeaving: string = "Already leaving??";
export const YesLogOut: string = "Yes, Log out";
export const ParentToggleTitle: string = "Remove your complete account from your phone or tablet to sign out of the Gmail app.";
export const ConnectNewAccount: string = "Connect new account";
export const ConnectNewRegisterAccount: string = "Register";
export const SignIn: string = "Sign in";
export const SignUp: string = "Sign Up";
export const FirstName: string = "First Name";
export const LastName: string = "Last Name";
export const EmailAddress: string = "Email Address";
export const MofiEmail: string = "Mofitheme@gmail.com";
export const EnterYourFirstName: string = "Enter your first-name";
export const EnterYourLastName: string = "Enter your last-name";
export const TermsAndCondition: string = "You accept our Terms and Privacy Policy by clicking Submit below.";
export const ExtraLargeModal: string = "Extra large modal";
export const WebDesign: string = "Web Design";
export const StartWithYourGoals: string = "Start with your goals";
export const FullscreenModal: string = "Fullscreen modal";
export const GekkoCo: string = "Gekko Co";
export const FirstNameRequired: string = "First name is required";
export const LastNameRequired: string = "Last name is required";
export const PhoneRequired: string = "Please enter number for phone";
export const EmailRequired: string = "Please enter proper email address";
export const AddressRequired: string = "Please right your address";
export const CityRequired: string = "select one city";
export const StateRequired: string = "select one state";
export const PincodeRequired: string = "Required integer";
export const CheckoutRequired: string = "Need to mark";

//Ui Kits- Alert
export const LinkColorDarkTheme: string = "Link Color In Dark Theme";
export const LinkColorLightTheme: string = "Link Color In Light Theme";
export const OutlineDarkLightAlerts: string = "Outline Dark And Light Alerts";
export const AlertsWithIconsTextActions: string = "Alerts With Icons and Text Actions";
export const DismissingDarkAlert: string = "Dismissing Dark Alerts";
export const DismissingLightAlert: string = "Dismissing Light Alerts";
export const LiveAlerts: string = "Live Alert";
export const ShowLiveAlert: string = "Show live alert";
export const LeftBorderAlerts: string = "Left Border Alert";
export const AdditionalContents: string = "Additional content";
export const PleaseCheckYourNotifications: string = "Please! Check your notifications";

//Ui Kits- Tooltip
export const TooltipSmall: string = "tooltip";
export const BasicTooltips: string = "Basic Tooltip";
export const MagicPleaseHoverMe: string = "It's magic please hover me...";
export const InlineTooltipContent: string = "Inline Tooltip Content";
export const ColoredTooltips: string = "Colored Tooltip ";
export const DirectionsTooltip: string = "Tooltip  Directions";
export const TooltipOnTop: string = "Tooltip on tops";
export const HTMLElementsWithHoverEffect: string = "HTML Elements With Hover Effect";
export const NotificationsReceived: string = "Notifications Received";
export const FilledTooltips: string = "Filled Tooltip";
export const TooltipPrimary: string = "Tooltip Primary";
export const ThankYouBold: string = "<b>Thank</b> <em>you</em>";
export const ThankYouItalic: string = "<i>Thank </i> <u>you</u>";
export const Primary: string = "Primary";

//Bonus Ui - Scrollable
export const CustomScrollbars: string = "Custom Scrollbar";
export const SmallSizeScrollbars: string = "Small Size Scrollbar";
export const SolutionBusinessTransformation: string = "Solution for Business Transformation";
export const BadgesScrollbars: string = "Badges Scrollbar";
export const ProfileScrollableTitle: string = "Profile Scrollable";
export const ScrollableContents: string = "Scrollable Content";
export const HorizontalScrollbars: string = "Horizontal Scrollbar ";
export const BothSideVisibleScrollbars: string = "Both Side Visible Scrollbar";

//Bonus Ui - Toasts
export const Toasts: string = "Toasts";
export const LiveToasts: string = "Live Toast";
export const TopRightToasts: string = "Top-right toast";
export const BottomRightToasts: string = "Bottom-right toast";
export const TopLeftToasts: string = "Top-left toast";
export const BottomLeftToasts: string = "Bottom-left toast";
export const YourAccountWillBePermanentlyDeleted: string = "Your account will be permanently deleted?";
export const ImNotSure: string = "I'm not sure";
export const RemoveMyAccount: string = "Remove My Account";
export const ColorsScheme: string = "Colors Schemes";
export const StackingToast: string = "Stacking Toasts";
export const TranslucentToast: string = "Translucent Toasts";
export const DefaultToasts: string = "Default Toast";
export const UniqueToasts: string = "Unique Toast";
export const ToastPlacements: string = "Toast Placement";

//Bonus Ui - Dropzone
export const DefaultFileUploads: string = "Default File Upload";
export const PreviewImage: string = "Image Preview ";
export const SingleFileUploads: string = "Single File Upload";
export const MultiFileUploads: string = "Multi File Upload";
export const DropFilesHereOrClickToUpload: string = "Drop files here or click to upload.";

//Bonus Ui - Sweet Alerts
export const BasicExamples: string = "Basic Example";
export const ClickIt: string = "Click it!";
export const Surprise: string = "Surprise!";
export const TitleWithATextUnder: string = "Title With A Text Under";
export const InfoAlerts: string = "Info Alert";
export const Informational: string = "Informational";
export const WarningAlerts: string = "Warning Alert ";
export const SweetWarningButton: string = "Warning";
export const PikachuAlerts: string = "Pikachu Alert";
export const Pikachu: string = "Pikachu";
export const QuestionsAlerts: string = "Questions Alert ";
export const QuestionsState: string = "Questions state";
export const UsernameAlerts: string = "Username Alert";
export const SuccessMessages: string = "Success Message";
export const LoginSuccessfully: string = "Login successfully";
export const DangerAlerts: string = "Danger Alert ";
export const DangerMode: string = "Danger mode";
export const WarningModes: string = "Warning Mode";
export const AlertMode: string = "Alert mode";
export const Timer: string = "Timer";
export const AjaxRequestMovies: string = "AJAX Request Movie";
export const MovieMode: string = "Movie mode";
export const Username: string = "Username";

//Bonus Ui - Paginations
export const DefaultPaginations: string = "Default Pagination";
export const PaginationWithActiveAndDisabled: string = "Pagination With Active And Disabled";
export const PaginationWithIcon: string = "Pagination With Icons";
export const RoundedPaginations: string = "Rounded Pagination";
export const PaginationAlignments: string = "Pagination Alignment";
export const PaginationSizings: string = "Pagination Sizing";
export const NextData: string[] = ["1", "2", "3", "...", "20"];
export const Previous: string = " Previous";
export const Next: string = " Next";

//Bonus Ui - Breadcrumb
export const Breadcrumbs: string = "Breadcrumb";
export const BreadcrumbHome: string = "Home";
export const BreadcrumbUiKits: string = "Ui Kits";
export const BreadcrumbAlert: string = "Alert";
export const BreadcrumbProgress: string = "Progress";
export const BreadcrumbBonusUi: string = "Bonus Ui";
export const BreadcrumbTable: string = "Table";
export const BreadcrumbBootstrapTable: string = "Bootstrap Tables";
export const DefaultBreadcrumbs: string = "Default Breadcrumb";
export const DividerBreadcrumbs: string = "Divider Breadcrumb";
export const WithIconsBreadcrumbs: string = "With Icons Breadcrumb";
export const VariationOfBreadcrumbs: string = "Variation Of Breadcrumb";
export const ColoredBreadcrumbs: string = "Colored Breadcrumb";

//Icon
export const FlagIcon: string = "Flag Icons";
export const FontAwesomeIcons: string = "Font Awesome Icon";
export const Currency: string = "Currency";
export const WebApp: string = "Web App";
export const Spinner: string = "Spinner";
export const FormControl: string = "Form Control";
export const TextEditor: string = "Text Editor";
export const Directional: string = "Directional";
export const VideoPlayer: string = "Video Player";
export const BrandPlayer: string = "Brand Player";
export const Medical: string = "Medical";
export const IcoIcon: string = "ICO Icon";
export const Abstract: string = "Abstract";
export const Sport: string = "Sport";
export const Social: string = "Social";
export const Weather: string = "Weather";
export const WebApplication: string = "Web Application";
export const Travel: string = "Travel";
export const Transport: string = "Transport";
export const Multimedia: string = "Multi media";
export const MobileUI: string = "Mobile UI";
export const Mathematical: string = "Mathematical";
export const Animal: string = "Animal";
export const Brand: string = "Brand";
export const Construction: string = "Construction";
export const Device: string = "Device";
export const Education: string = "Education";
export const FileType: string = "File Type";
export const Food: string = "Food";
export const Law: string = "Law";
export const Business: string = "Business";
export const Emoticon: string = "Emoticon";
export const KidsToys: string = "Kids & Toys";
export const Payment: string = "Payment";
export const Person: string = "Person";
export const ThemifyIcon: string = "Themify Icon";
export const ArrowsDirection: string = "Arrows & Direction ";
export const Control: string = "Control";
export const FeatherIcons: string = "Feather Icons";
export const WhetherIcon = "Whether Icon";
export const whetherIconsWithAnimations = "Whether Icons With Animations";
export const CopyText = "Copy text";
export const Markup = "Markup";

//Buttons
export const DefaultStyles: string = "Default Style";
export const Buttons: string = "Button";
export const DefaultButtonsHeading: string = "Default Buttons";
export const LargeButtonsHeading: string = "Large Buttons";
export const SmallButtonsHeading: string = "Small Buttons";
export const ExtraSmallButtonsHeading: string = "Extra Small Buttons";
export const ActiveButtonsHeading: string = "Active Buttons";
export const DisabledButtonsHeading: string = "Disabled Buttons";
export const CustomStateButtonsHeading: string = "Custom State Buttons";
export const OutlineButtonsHeading: string = "Outline Buttons";
export const BoldBorderOutlineButtonsHeading: string = "Bold Border Outline Buttons";
export const OutlineLargeButtonsHeading: string = "Outline Large Buttons";
export const OutlineSmallButtonsHeading: string = "Outline Small Buttons";
export const OutlineExtraSmallButtonsHeading: string = "Outline Extra Small Buttons";
export const DisabledOutlineButtonsHeading: string = "Disabled Outline Buttons";
export const GradientButtonsHeading: string = "Gradient Buttons";
export const Links: string = "Link";
export const CustomButtons: string = "Custom state buttons";
export const ButtonHeading: string = "Button";
export const NestingButtonSpan: string = `Make nesting buttons`;
export const Submit: string = "Submit";
export const FlatButton: string = "Flat Buttons";
export const EdgeButton: string = "Edge Buttons";
export const RaisedButton: string = "Raised Buttons";
export const ButtonGroups: string = "Button Group";
export const RadioButtonGroup: string = "Radio Button Group";
export const CheckBoxButtonGroup: string = "CheckBox Button Group";
export const Option1: string = "Option 1";
export const Option2: string = "Option 2";
export const Action: string = "Action";
export const AnotherAction: string = "Another Action";
export const Header: string = "Header";
export const Vertical: string = "Vertical";
export const BasicButtonGroups: string = "Basic button group";
export const Left: string = "Left";
export const Middle: string = "Middle";
export const Right: string = "Right";
export const EdgesButtonGroups: string = "Edges button group";
export const FlatButtonGroups: string = "Flat button group";
export const LargeButtonGroups: string = "Large Button group";
export const LargeEdgesButtonGroups: string = "Large Edges Button group";
export const OutlineCustomButtonGroupTitle: string = "Outline Custom button group";
export const OutlineButtonGroups: string = "Outline button group";
export const OutlineEdgeButton: string = "Outline Edges button";
export const OutlineFlatButtons: string = "Outline flat button";
export const RadioButtonGroups: string = "Radio button group";
export const CheckBoxButtonGroups: string = "Radio button group";
export const NestingButton: string = "Nesting";
export const DropdownLink: string = "Dropdown link";
export const VerticalGroupButton: string = "Vertical";
export const RememberMe: string = "Remember me";
export const Meditations: string = "Meditations";

//Charts - Apex charts
export const BasicAreaCharts: string = "Basic Area Chart ";
export const AreaSpalineCharts: string = "Area Spaline Chart";
export const BarCharts: string = "Bar chart";
export const ColumnCharts: string = "Column Chart ";
export const BubbleCharts: string = "3d Bubble Chart";
export const SteplineCharts: string = "Stepline Chart ";
export const ChartColumn: string = "Column Chart";
export const PieCharts: string = "Pie Chart ";
export const DonutChart: string = "Donut Chart";
export const MixedCharts: string = "Mixed Chart";
export const CandlestickCharts: string = "Candlestick Chart ";
export const RadarCharts: string = "Radar Chart";
export const RadialBarCharts: string = "Radial Bar Chart";

//Charts - Google charts
export const AreaChartOne: string = "Area Chart 1";
export const ColumnChartOne: string = "Column Chart 1";
export const AreaChartTwo: string = "Area Chart 2";
export const ColumnChartTwo: string = "Column Chart 2";
export const GanttCharts: string = "Gantt Chart";
export const LineCharts: string = "Line Chart";
export const ComboCharts: string = "Combo Chart";
export const BarChartTwo: string = "bar-chart2";
export const WordTreeChart: string = "word tree";
export const PieChartOne: string = "Pie Chart 1";
export const PieChartTwo: string = "Pie Chart 2";
export const PieChartThree: string = "Pie Chart 3";
export const PieChartFour: string = "Pie Chart 4";

//Charts - ChartJS charts
export const ChartJSBarChart: string = "Bar Chart";
export const ChatJSLineGraph: string = "Line Graph";
export const ChatJSRadarGraph: string = "Radar Graph";
export const ChatJSLineChart: string = "Line Chart";
export const ChatJSPolarChart: string = "Polar Chart";

//sample page
export const SamplePage: string = "Sample Page";
export const SampleCard: string = "Sample Card";

//Authentication
export const SignInToAccount: string = "Sign in to account";
export const EmailAddressLogIn = "Email Address";
export const Password = "Password";
export const RememberPassword = "Remember password";
export const OrSignInWith: string = "Or Sign in with";
export const EmailAddressSignUp = "Email Address";
export const PasswordSignUp = "Password";
export const AuthSignIn: string = "Sign in";
export const EnterYourPassword: string = "Enter your Password";
export const DoneButton: string = "Done";
export const EnterYourEmailPasswordToLoginWizard: string = "Enter your email & password to login";
export const FirstNameWizardPlaceholder: string = "Johan";
export const LastNameWizardPlaceholder: string = "Deo";
export const ContactNameWizardPlaceholder: string = "123456789";
export const EmailAddressWizardPlaceholder: string = "name@example.com";
export const PasswordWizard: string = "Password";
export const PasswordWizardPlaceholder: string = "Password";
export const Logout: string = "Log out";

//Miscellaneous - Gallery
export const ImageGallery: string = "IMAGE GALLERY";
export const MyPortfolioTitle: string = "My Portfolio";
export const MasonryGallery: string = "Masonry Gallery";
export const MasonryGalleryCap: string = "MASONRY GALLERY";
export const PortfolioTitle: string = "Portfolio Title";
export const ImageHoverEffects: string = "Image Hover Effects";

//Editors
export const InlineEditors: string = "Inline Editor";
export const EditorsText: string = "Your title";
export const MDEEditor: string = "MDE Editor";
export const MdeEditorExample = "MDE Editor Example";
export const SecondExample: string = "Second Example";
export const Instructions: string = "Instructions";

//Forms Validation
export const ValidationForms: string = "Validation Forms";
export const FormValidationTooltip: string = "Tooltip form validation";
export const LooksGood: string = "Looks good!";
export const UsernameFeedback: string = "Please choose a unique and valid username.";
export const City: string = "City";
export const Zip: string = "Zip";
export const State: string = "State";
export const StateChoose: string = "Choose...";
export const CityFeedback: string = "Please provide a valid city.";
export const StateFeedback: string = "Please select a valid state.";
export const ZipFeedback: string = "Please provide a valid zip.";
export const SubmitButton: string = "Submit form";
export const MarkFirstNamePlaceholder: string = "Mark";
export const OttoLastNamePlaceholder: string = "Otto";
export const BrowserDefault: string = "Browser defaults";
export const FirstNamePlaceholder: string = "First name";
export const EmailPlaceholder: string = "pesamof475@saeoil.com";
export const PasswordBrowserDefault: string = "Password";
export const ChooseFile: string = "Choose file";
export const SelectYourPaymentMethod: string = "Select your payment method";
export const Visa: string = "Visa";
export const MasterCard: string = "MasterCard";
export const Paypal: string = "Paypal";
export const PayMethodTitle: string = "Select your payment method";
export const AgreeToThePolicies: string = "I agree to the policies";
export const SureInformation: string = "Are you sure above information are true";
export const ValidationsForms: string = "Validation form";
export const FirstNameError: string = "Please enter your valid firstname";
export const FirstNameFeedback: string = "Please enter your valid";
export const PasswordValidation: string = "Password";
export const PasswordFeedback: string = "Please enter your valid password";
export const StateInvalidFeedback: string = "Please select a valid state.";
export const CityInvalidFeedback: string = "Please provide a valid city..";
export const ZipInvalidFeedback: string = "Please provide a valid zip.";
export const VISA: string = "VISA";
export const SelectThemeTitle: string = "Select Your Favorite Pixelstrap theme";
export const ThemeError: string = "Invalid select feedback";
export const ChooseFiles: string = "Choose File";
export const InvalidFormFileSelected: string = "Invalid form file selected";
export const TextAreaPlaceHolder: string = "Enter your comment";
export const TextAreaError: string = "Please enter a message in the textarea.";
export const TermsError: string = "You must agree before submitting.";
export const AgreeCondition: string = "Agree to terms and conditions";
export const AgreeSubmitting: string = "You must agree before submitting.";

//Base Input
export const BaseInputs: string = "Base inputs";
export const FormBasic: string = "Basic form";
export const EmailLabel: string = "Email";
export const EmailPlaceHolder: string = "Enter Your Email";
export const PasswordLabel: string = "Password";
export const PasswordPlaceholder: string = "Enter Your Password";
export const CheckMeOut: string = "Check me out";
export const SignInButton: string = "Sign in";
export const FormFloating: string = "Floating form";
export const EmailFloatingPlaceholder: string = "name@example.com";
export const PasswordFloatingPlaceholder: string = "Password";
export const FloatingPasswordPlaceholder: string = "Password";
export const SelectSizings: string = "Select sizing";
export const WhatsYourHobbies: string = "What's Your Hobbies";
export const FormControlSizings: string = "Form control sizing";
export const FormControlSizingsPlaceholder: string = ".form-control-sm";
export const FileInputs: string = "File input";
export const FlatInputStyles: string = "Flat input style";
export const SmallFileInputExample: string = "Small file input example";
export const LargeFileInputExample: string = "Large file input example";
export const SelectYourFavoriteRomanNumber: string = "Select your favorite roman number";
export const SelectYourMultiplePaintings: string = "Select your multiple paintings";
export const PleaseDoComments: string = "Please do comments";
export const BasicHtmlInputControls: string = "Basic HTML input control";
export const BasicPlaceholder: string = "Placeholder";
export const BasicPlaceholderPlace: string = "Type your title in Placeholder";
export const BasicPassword: string = "Password";
export const PasswordInputPlaceholder: string = "Password input";
export const BasicNumber: string = "Number";
export const NumberPlaceholder: string = "Number";
export const BasicTelephone: string = "Telephone";
export const BasicTelephonePlaceholder: string = "91-(999)-999-999";
export const URLs: string = "URL";
export const URLsValue: string = "https://getbootstrap.com";
export const BasicDateAndTime: string = "Date and time";
export const FullDateAndTime: string = "2018-01-19T18:45:00";
export const BasicDate: string = "Date";
export const FullDate: string = "2018-01-01";
export const BasicMonth: string = "Month";
export const FullMonth: string = "2018-01";
export const BasicWeek: string = "Week";
export const FullWeek: string = "BasicWeek";
export const BasicDatalistExample: string = "Datalist example";
export const ListPlaceholder: string = "Look up your nation...";
export const BasicTime: string = "Time";
export const BasicColorPicker: string = "Color picker";
export const BasicMaximumLength: string = "Maximum Length";
export const MaximumLengthPlaceholder: string = "Content must be in 6 characters";
export const BasicStaticText: string = "Static Text";
export const StaticTextData: string = "Hello !... This is my magical text";
export const BasicSubmitButton: string = "Submit";
export const BasicCancelButton: string = "Cancel";
export const BasicFloatingInputControls: string = "Basic floating input control";
export const FloatingValidInput: string = "Valid input ";
export const InputWithValue: string = "Input with value";
export const InvalidInput: string = "Invalid input";
export const FloatingComments: string = "Comments";
export const FloatingEmail: string = "Email";
export const FloatingPassword: string = "Password";
export const FloatingComment: string = "Comments";
export const FloatingCommentPlaceholder: string = "Leave a comment here";
export const FloatingCommentLabel: string = "Comments";
export const InputWithValuePlaceholder: string = "name@example.com";
export const InvalidInputPlaceholder: string = "name@example.com";
export const LayOutPlaceholder: string = "name@example.com";
export const LayOutDefaultValue: string = "mdo@example.com";
export const CommentsPlaceholder: string = "Comments";
export const InputWithValuePlaceholderValue: string = "test@example.com";
export const InvalidInputPlaceholderValue: string = "test@example.com";
export const FloatingEmailLabel: string = "Email address";
export const FloatingOpenLabel: string = "Open this select menu";
export const FloatOpenFloatingLabel: string = "Works with selects";
export const FloatingInputGroup: string = "Input group";
export const FloatingInputGroupLabel: string = "Username";
export const FloatingInputGroupFeed: string = "Please choose a username.";
export const FloatingLayout: string = "Layout";
export const FloatingCancelButton: string = "Cancel";
export const FloatingSubmitButton: string = "Submit";
export const EdgesInputStyles: string = "Edges input style";
export const EdgeEmailAddress: string = "Email address";
export const EdgeEmailAddressPlaceholder: string = "name@example.com";
export const EdgePassword: string = "Password";
export const EdgePasswordPlaceholder: string = "Password";
export const SelectYourFavoritePixelstrapTheme: string = "Select your favorite pixelstrap theme";
export const DefaultFileInputExamples: string = "Default file input example";
export const EdgeDefaultInput: string = "Default Input";
export const EdgeDefaultInputPlaceholder: string = "Default Input";
export const EdgeMale: string = "Male";
export const EdgeFemale: string = "Female";
export const EdgeComments: string = "Comments";
export const EdgeSubmit: string = "Submit";
export const EdgeCancel: string = "Cancel";
export const RaiseInputStyles: string = "Raise input style";
export const RaisedEmailAddress: string = "Email address";
export const RaisedEmailAddressPlaceholder: string = "name@example.com";
export const RaisedPassword: string = "Password";
export const RaisedPasswordPlaceholder: string = "Password";
export const RaisedSubmit: string = "Submit";
export const RaisedCancel: string = "Cancel";
export const RaisedSelectYourFavoritePixelstrapTheme: string = "Select your favorite pixelstrap theme";
export const SelectTheColorYouLikeBelow: string = "Select the color you like below";
export const RaisedComments: string = "Comments";

//Checkbox & Radio
export const CheckboxAndRadio: string = "Checkbox & Radio";
export const DefaultCheckboxs: string = "Default checkbox";
export const DefaultCheck: string = "Default Checks";
export const Defaultcheckboxes: string = "Default checkbox";
export const CheckedCheckbox: string = "Checked checkbox";
export const DisabledChecks: string = "Disabled Checks";
export const Indeterminate: string = "Indeterminate";
export const IndeterminateCheckbox: string = "Indeterminate checkbox";
export const CustomCheckboxs: string = "Custom checkbox";
export const BorderedCheckbox: string = "Bordered Checkbox ";
export const PrimaryCheckboxPrimary: string = "Primary - checkbox-primary";
export const IconCheckbox: string = "Icon Checkbox ";
export const FilledCheckbox: string = "Filled Checkbox";
export const WarningCheckboxSolidWarning: string = "Warning - checkbox-solid-warning ";
export const DefaultRadios: string = "Default radio";
export const CustomRadio: string = "Custom Radios";
export const DefaultRadioLabel: string = "Default radio";
export const DefaultCheckedRadio: string = "Default checked radio";
export const ImagesWithCheckboxs: string = "Images with checkbox";
export const ImagesWitRadio: string = "Images with radio";
export const Custom: string = "Custom";
export const CustomRadios: string = "Custom radio";
export const BorderedRadios: string = "Bordered Radio";
export const KohoTheme: string = "Koho Theme";
export const IconsRadios: string = "Icons Radio";
export const FilledRadios: string = "Filled Radio";
export const ProductRadio: string = "Product";
export const DefaultSwitche: string = "Default switches";
export const CustomSwitches: string = "Custom Switches";
export const DefaultSwitchCheckboxInput: string = "Default switch checkbox input";
export const CheckedSwitchCheckboxInput: string = "Checked switch checkbox input";
export const InlineInputType: string = "Inline input-types";
export const InlineCheckbox: string = "Inline Checkbox";
export const InlineRadio: string = "Inline Radios";
export const InlineSwitches: string = "Inline Switches";
export const AnimatedButton: string = "Animated buttons";
export const SelectYourPaymentMethods: string = "Select your payment method";
export const VisaAnimated: string = "Visa";
export const InstagramAnimated: string = "Instagram";
export const WhatIsYourFavoriteSocialMedia: string = "What is your favorite social media?";
export const BasicRadioAndCheckboxs: string = "Basic radio and checkbox";
export const SimpleCheckbox: string = "Simple Checkbox";
export const BasicRadioAndCheckboxBlog: string = "Blog";
export const BasicRadioAndCheckboxSimpleRadios: string = "Simple Radios";
export const BasicRadioAndCheckboxMaps: string = "Maps";
export const RadioToggleButton: string = "Radio toggle buttons";
export const RadioChecked: string = "Checked";
export const OutlinedCheckboxStyle: string = "Outlined checkbox styles";
export const SingleToggle: string = "Single toggle";
export const ButtonChecked: string = "Checked";
export const ButtonCheckedSuccessRadio: string = "Checked success radio";
export const ButtonDarkRadio: string = "Dark radio";

//Input groups
export const InputGroup: string = "Input groups";
export const ButtonAddon: string = "Button addons";
export const SubmitButtonAddon: string = "Submit";
export const SubmitButtonAddonPlaceHolder: string = "Recipient's username";
export const AddonPlaceHolder: string = "Recipient's username";
export const CustomForm: string = "Custom forms ";
export const OptionsFormGroup: string = "Options";
export const PixelstrapThemeTitle: string = "Select Your Favorite Pixelstrap theme";
export const FavoriteColorsTitle: string = "Select Your Favorite Colors";
export const FavoriteChocolatesTitle: string = "Select Your Favorite Chocolates";
export const FavoriteThemeTitle: string = "Select Your Favorite Theme";
export const CustomFormSubmit: string = "Submit";
export const CustomFileInputs: string = "Custom file input";
export const CustomFileInputsUpload: string = "Upload";
export const CustomFileInputsVerify: string = "Verify";
export const CustomFileInputsSubmit: string = "Submit";
export const ButtonsWithDropdown: string = "Buttons with dropdowns";
export const ButtonsWithDropdownTitle: string = "Dropdown";
export const ToggleDropdown: string = "Toggle Dropdown";
export const SegmentedButton: string = "Segmented buttons";
export const SegmentedButtonInfo: string = "Info";
export const SegmentedButtonSecondary: string = "Secondary";
export const CheckboxesAndRadio: string = "Checkboxes and radios";
export const Sizings: string = "Sizing";
export const SmallInput: string = "Small";
export const DefaultInput: string = "Default";
export const LargeInput: string = "Large";
export const MultipleInput: string = "Multiple inputs";
export const FirstAndLastName: string = "First and last name";
export const BasicInputGroup: string = "Basic input groups";
export const BasicInputGroupBasic: string = "Basic";
export const YourVanityUrl: string = "Your vanity URL";
export const WithTextarea: string = "With textarea";
export const UsernamePlaceholder: string = "Username";
export const RecipientPlaceholder: string = "Recipient's username";
export const ServerPlaceholder: string = "Server";
export const Wrapping: string = "Wrapping";
export const FlexNowrapCodeText: string = ".flex-nowrap";
export const ButtonBasicInputSubmit: string = "Submit";
export const ButtonBasicInputCancel: string = "Cancel";
export const VariationOfAddon: string = "Variation of addons";
export const LeftAddon: string = "Left Addon";
export const RightAddon: string = "Right Addon";
export const JointAddon: string = "Joint Addon";
export const LeftAddonPlaceholder: string = "Email";
export const RightAddonPlaceholder: string = "Recipient's username";
export const LeftAndRightAddon: string = "Left & Right Addon";
export const SolidStyle: string = "Solid style";
export const FlatStyle: string = "Flat style";
export const RaiseStyle: string = "Raise style";
export const LeftAndRight: string = "Left & Right Addon";
export const VariationOfAddonsSubmit: string = "Submit";
export const VariationOfAddonsCancel: string = "Cancel";

//Input Mask
export const InputMasks: string = `Input masks`;
export const DefaultInputMask: string = "Default Input Mask";
export const DateFormatHeading: string = "Date Format";
export const Date: string = "Date";
export const DateFormatType: string = "Date format type";
export const TimeFormatHeading: string = "Time Format";
export const TimeFormatType: string = "Time format type";
export const HourMonthType: string = "Hour/month type";
export const CurrencyPlaceholder: string = "hh:mm";
export const Prefix: string = "Prefix";
export const PrefixPlaceholder: string = "Prefix-xxxx-xxxx-xxxx";
export const Delimiter: string = "Delimiter";
export const DelimiterPlaceholder: string = "xxx·xxx·xxx";
export const PhoneNumber: string = "Phone Number";
export const PhoneNumberPlaceholder: string = "(xxx)xxx-xxxx";
export const CardNumber: string = "Card Number";
export const CardNumberPlaceholder: string = "xxxx xxxx xxxx xxxx";
export const Tailprefix: string = "Tail prefix";
export const TailprefixPlaceholder: string = "0000.00€";

//Mega options
export const MegaOptions: string = "Mega options";
export const VariationRadios: string = "Variation radio";
export const VariationCheckboxs: string = "Variation checkbox";
export const ChooseActivities: string = "Which of the following activities do you enjoy doing in your free time?";
export const UpgradeTitle: string = "It's time to";
export const UpgradeSpanText: string = "upgrade";
export const DefaultStyleMegaOptions: string = "Default style";
export const WithoutBordersStyles: string = "Without borders style";
export const SolidBorderStyles: string = "Solid border style";
export const OfferStyleBorders: string = "Offer style border";
export const InlineStyles: string = "Inline style";
export const VerticalStyles: string = "Vertical style";
export const HorizontalStyles: string = "Horizontal style";

//Datepicker
export const CalendarDefault: string = "Default calendar";
export const CalendarBootstrap: string = "Reactstrap calendar";
export const DatePickers: string = "Date picker";
export const CustomizingConjunction: string = "Customizing Conjunction";
export const DefaultDates: string = "Default Date";
export const DisabledDates: string = "Disabled Dates";
export const HumanFriendly: string = "Human Friendly";
export const MinMaxValue: string = "Min-Max Value";
export const MultiplesDates: string = "Multiples Dates";
export const Range: string = "Range";
export const TimePickerTitle: string = "Time picker";
export const TimePickers: string = "Time Picker";
export const DatePicker: string = "DatePicker";
export const MultiplesDatesHeading: string = "Multiples Dates";
export const RangeDatePicker: string = "Range";
export const PreloadingDates: string = "Preloading Dates";
export const TimPickers: string = "Time picker";
export const TimePickerHeading: string = "Time Picker";
export const hourPicker: string = "24-hour Time Picker";
export const TimePickerLimits: string = "Time Picker W/Limits";
export const PreloadingTime: string = "Preloading Time";
export const TimePickerRange: string = "TimePicker with Limited Time Range";
export const TimePickerMinMaxRange: string = "TimePicker with Min/Max Time Range";
export const DateWithTime: string = "Date With Time";
export const DateAndTimeHeading: string = "Date and time";
export const Month: string = "Month";
export const Week: string = "Week";
export const Time: string = "Time";

//Switches
export const CustomSwitchs: string = "Custom switch";
export const IconsSwitchs: string = "Icons switch";
export const UncheckedSwitches: string = "Unchecked switch";
export const BordersWithIcon: string = "Borders with icons";
export const DisabledOutlineSwitches: string = "Disabled outline switch";
export const VariationOfSwitche: string = "Variation of switches";
export const SwitchSizings: string = "Switch sizing";
export const SwitchWithIcon: string = "Switch with Icons";

//Typeahead
export const BasicTypeaheads: string = "Basic typeahead";
export const statesOfUSA: string = "States of USA";
export const PreFetchHeading: string = "Prefetch";
export const BloodHoundHeading: string = "Bloodhound (Suggestion Engine)";
export const RemotetypeAheadHeading: string = "Remote typeahead";
export const CustomTemplate: string = "Custom templates";
export const MultipleSectionWithHeader: string = "Multiple sections with headers";
export const ScrollableDropDownMenu: string = "Scrollable Dropdown Menu";
export const RTLSupport: string = "RTL Support";

//Two factor
export const TwoFactorAuthenticationHeading: string = "Two-factor authentication";
export const FactorAuthentication: string = "2 factor authentication";
export const VerificationCodeHeading: string = "Verification code";
export const OtpCodeSent: string = "We've sent a verification code to";
export const OtpCode: string = "Your OTP Code here:";
export const Verify: string = "Verify";
export const Call: string = " Call";
export const ModalTitle: string = "Modal title";
export const ScanQRCode: string = "Scan QR code";
export const EmailVerificationHeading: string = "Email verification";
export const EnterQRCode: string = "Enter QR Code";
export const PleaseEnterTheCodeHere: string = "Please enter the code here";

//Data Tables - Basic Data Tables
export const ZeroConfiguration: string = "Zero Configuration";
export const SearchTableButton: string = "Search";
export const StateSavingTitle: string = "State saving";
export const ScrollVerticalDynamicHeightTitle: string = "Scroll - vertical, dynamic height";

//Data Tables - Advance Init
export const StockResultTitle: string = `Stock Result`;
export const RowCreateCallBackSpan: string = "Row Create Callback";
export const APIDataTables: string = "API DataTables";
export const AddRowsTitle: string = "Add rows";
export const AddNewRowButton: string = "Add new row";
export const ChildrenRowsTitle: string = "Child rows (show extra / detailed information)";
export const ApiFullName: string = "Full Name: ";
export const ExtraInfo: string = "Extra info ";
export const ApiExtensionNumber: string = "Extension number: ";
export const ApiExtraInfo: string = "'And any further details here (images etc)...'";
export const RowsSelectionAndDeletions: string = "Row Selection And Deletion (Single Row)";
export const DeleteSelectDataButton: string = "Delete Row";
export const CustomFilteringSearch: string = "Custom filtering - range search";
export const MinimumAge: string = "Minimum age: ";
export const MaximumAge: string = "Maximum age:	";
export const DATASourceDataTables: string = "DATA Source DataTables";
export const HtmlTableTittle: string = "HTML (DOM) sourced data";
export const AjaxSourcedDataHeading: string = "Ajax sourced data";
export const JavascriptSourcedDataHeading: string = "Javascript sourced data";
export const ServerSideProcessingHeading: string = "Server-side processing";

// Dashboard
export const GoodDayLenaMiller: string = "Good day, Lena Miller";
export const GoPremium: string = "Go Premium";
export const OpeningOfLeaflet: string = "Opening of leaflets";
export const CustomerTransactions: string = "Customer Transaction";
export const Notifications: string = "Notifications";
export const UpcomingAppointment: string = "Upcoming Appointments";
export const ActiveMember: string = "Active Members";
export const SalesbyProduct: string = "Sales by Product";
export const SalesStatistics: string = "Sales Statistic";
export const ShiftsOverviews: string = "Shifts Overview";
export const ProjectStatusHeading: string = "Project Status";
export const RecentProject: string = "Recent Projects";
export const TotalProjects: string = "Total Project";
export const CurrentlyRunning: string = "Currently Running";
export const ProjectsOverviews: string = "Projects Overview";
export const ClientsActivity: string = "Client's activity of 2023";
export const WebsiteDesign: string = "Website Design";
export const TaskCompleted: string = "Task Completed";
export const SocialPostDesign: string = "Social Post Design";
export const PodcastWebdesign: string = "Podcast Web design";
export const CryptoDashboard: string = "Crypto Dashboard";
export const TodaysTasks: string = "Today’s Tasks";
export const NFTillustrarionPackage: string = "NFT illustrarion Package";
export const PodcastlandingPage: string = "Podcast landing Page";
export const DeliveryFoodApp: string = "Delivery Food App";
export const RunningEvent: string = "Running Events";
export const UpgradePlan: string = "Upgrade Plan";
export const ViewProject: string = "View Project";
export const OnlineCourseTimelines: string = "Online Course Timeline";
export const TotalSell: string = "Total Sells";
export const OrdersValue: string = "Orders Value";
export const DailyOrders: string = "Daily Orders";
export const DailyRevenue: string = "Daily Revenue";
export const SalesOverviews: string = "Sales Overview";
export const RecentCustomer: string = "Recent Customers";
export const RevenueByCategoryTitle: string = "Revenue By Category";
export const UserContinent: string = "User by Continent";
export const AllOverCountriesSales: string = "All Over Countries Sale";
export const Color: string = "Color";
export const NFTillustrationPackage: string = "NFT illustration Package";
export const SpecialDiscount: string = "Special Discount";
export const Min: string = "Min";
export const Sec: string = "Sec";
export const TopSellerMonth: string = "Top seller of the month";
export const RecentOrder: string = "Recent Orders";
export const DealDayFrom: string = "Deal of the Day From ";
export const SelectSize: string = "Select size";

// Widgets
export const WebsiteDesigns: string = "Website Design";
export const SquareDashboard: string = "Square Dashboard";
export const Design3D: string = "3D Design";
export const Visitor: string = "Visitors";
export const UpcomingAppointments: string = "Upcoming Appointment";
export const MonthlyHistorys: string = "Monthly History";
export const SkillStatusHeading: string = "Skill Status";
export const OrdersStatusHeading: string = "Order Status";
export const LiveProduct: string = "Live Products";
export const TurnOver: string = "Turn over";
export const CryptocurrencyPrice: string = "Cryptocurrency Prices";
export const StockMarkets: string = "Stock Market";
export const Finances: string = "Finance";
export const MonthlySale: string = "Monthly Sales";
export const CryptoAnnotation: string = "Crypto Annotations";
export const OrdersStatus: string = "Order Status";
export const Uses: string = "Uses";
export const StudyStatistic: string = "Study Statistics";
export const UXDesign: string = "UX Design";
export const Illustrations: string = "Illustrations";
export const Assignments: string = "Assignments";
export const LiveMeetings: string = "Live Meeting";
export const ActivelyHour: string = "Actively Hours";
export const EnrolledClass: string = "Enrolled Classes";
export const MonthlyAttendances: string = "Monthly Attendance Report (Feb)";
export const Schedules: string = "Schedule";
export const FeaturedCourse: string = "Featured Courses";

//Project
export const ProjectLists: string = "Project List";
export const All: string = "All";
export const Doing: string = "Doing";
export const Done: string = "Done";
export const CreateNewProject: string = "Create New Project";
export const Issues: string = "Issues";
export const Resolved: string = "Resolved";
export const Comment: string = "Comment";
export const ProjectCreate: string = "Project Create";
export const ProjectTitle: string = "Project Title";
export const ProjectTitlePlaceholder: string = "Project name *";
export const ClientName: string = "Client name";
export const ClientNamePlaceholder: string = "Name client or company name";
export const ProjectProgress: string = "Project Progress";
export const ProjectProgressPlaceholder: string = "Enter project Progress";
export const ProjectStatus: string = "Project Status";
export const Hourly: string = "Hourly";
export const FixPrice: string = "Fix price";
export const Low: string = "Low";
export const Medium: string = "Medium";
export const High: string = "High";
export const Urgent: string = "Urgent";
export const Priority: string = "Priority";
export const PriorityPlaceholder: string = "Select Status";
export const ProjectSize: string = "Project Size";
export const ProjectSizePlaceholder: string = "Select Issues";
export const Small: string = "Small";
export const Big: string = "Big";
export const StartingDate: string = "Starting date";
export const EndingDate: string = "Ending date";
export const ResolvedPlaceholder: string = "Add Resolved issues";
export const CommentPlaceholder: string = "Add Comment";
export const EnterSomeDetails: string = "Enter some Details";
export const Add: string = "Add";
export const UploadProjectFiles: string = "Upload project file";
export const DropFileUploadText: string = "(This is just a demo dropzone. Selected files are ";
export const ActualFileUpload: string = " actually uploaded.)";

//Search Result
export const SearchWebsite: string = "Search Website";
export const SearchPages: string = "Search Pages";
export const SearchPixelStrap: string = `Search result for "Pixelstrap"`;
export const SearchDesc: string = "Accusamus et iusto odio dignissimos ducimus qui blanditiis.";
export const ImageAbout: string = "About 12,120 results (0.50 seconds)";
export const AllAbout: string = `About 6,000 results (0.60 seconds)`;

//To Do
export const ToDoHeading: string = "To-Do";
export const ToDoFilter: string = "To Do filter";
export const ToDoList: string = "To Do List";
export const ToDoPlaceholder: string = "Enter new task here. . .";
export const AllTask: string = "All Task";
export const TrashBin: string = "Trash";
export const Completed: string = "Completed";
export const Pending: string = "Pending";
export const InProcess: string = "In Process";
export const AddTask: string = "Add Task";

//Calendar
export const CalendarBasic: string = "Calender Basic";
export const DraggableEvents: string = "Draggable Events";
export const RemoveAfterDrop: string = "remove after drop";
export const CalendarFilter: string = "calendar filter";

//Social App
export const SocialApp: string = "Social App";
export const MyProfile: string = "My Profile";
export const MyPage: string = "My Page";
export const Likes: string = "Likes";
export const View: string = "View";
export const MutualFriend: string = "Mutual Friends";
export const ActivityFeed: string = "Activity Feed";
export const ELANAHeading: string = "ELANA";
export const MoreCommnets: string = "More Commnets";
export const CommentsSocialPlaceholder: string = "Post Your commnets";
export const ProfileIntro: string = "Profile Intro";
export const Facebook: string = "Facebook";
export const Dribbble: string = "Dribbble";
export const AddFriend: string = "Add Friend";
export const LatestPhoto: string = "Latest Photos";
export const Friends: string = "Friends";
export const PeopleKnow: string = "Pepole You May Know";
export const EducationAndEmploymentHeading: string = "Education and Employement";
export const HobbiesAndInterest: string = "Hobbies and Interests";
export const ActivityLogHeading: string = "Activity Log";
export const Followers: string = "Followers";
export const Following: string = "Following";
export const ViewProfile: string = "Viewed Your Profile";
export const Posts: string = "Posts";

//Contacts
export const ContactFilter: string = "contact filter";
export const NewContacts: string = "New Contacts";
export const AddContacts: string = " Add Contact";
export const Phone: string = "Phone";
export const Mobile: string = "Mobile";
export const AddCategory: string = "Add Category";
export const Personal: string = "Personal";
export const MobileNo: string = "Mobile No";
export const History: string = "History";
export const PrintViews: string = "Print preview";
export const Gender: string = "Gender";
export const FollowUp: string = "Follow up";
export const Ideas: string = "Ideas";
export const ContactHistory: string = "Contact History";
export const ContactCreated: string = "Contact Created";
export const Views: string = "Views";
export const Favorites: string = "Favorites";
export const Important: string = "Important";
export const Edit: string = "Edit";
export const Delete: string = "Delete";
export const General: string = "General";
export const Organization: string = "Organization";

//User
export const UserProfile: string = "User Profile";
export const Like: string = "Like";
export const Company: string = "Company";
export const AboutMe: string = "About me";
export const PostalCode: string = "Postal Code";
export const EditProfile: string = "Edit Profile";
export const MyProfiles: string = "My Profile";
export const Designer: string = "DESIGNER";
export const Bio: string = "Bio";
export const WebPlaceHolders: string = "http://Uplor.com";
export const UpdateProfile: string = "UpdateProfile";
export const AddProjectAndUpload: string = "Add project And Upload";
export const Update: string = "Update";
export const UserCards: string = "User Cards";

//Bookmarks
export const Bookmarks: string = "Bookmarks";
export const BookmarkFilter: string = "Bookmark filter";
export const NewBookmark: string = "New Bookmark";
export const AddBookmark: string = "Add Bookmark";
export const WebUrl: string = "Web Url";
export const Title: string = "Title";
export const Group: string = "Group";
export const Tags: string = "Tags";
export const CreateTag: string = "Create Tag";
export const NoBookmarksFound: string = "No Bookmarks Found.";
export const SharedWithMe: string = "Shared with me";
export const MyBookmark: string = " My bookmark";
export const EditBookmark: string = "Edit Bookmark";
export const MyBookmarks: string = "My Bookmarks";
export const CreatedByMe: string = "Created By Me";

//Ecommerce - Product page
export const ProductPage: string = "Product Page";
export const ProductTittle: string = "Women Pink shirt.";
export const PixelStrap: string = "Pixelstrap";
export const Availability: string = "Availability";
export const InStock: string = "In stock";
export const Seller: string = "Seller";
export const ABC: string = "ABC";
export const Fabric: string = "Fabric";
export const Cotton: string = "Cotton";
export const ShareIt: string = "share it";
export const RateNow: string = "Rate Now";
export const AddToCart: string = "Add To Cart";
export const BuyNow: string = "Buy Now";
export const AddToWishList: string = "Add To WishList";

//Ecommerce - Product
export const Filters: string = "Filters";
export const Featured: string = "Featured";
export const LowestPrices: string = "Lowest Prices";
export const HighestPrices: string = "Highest Prices";
export const Categorys: string = "Category";
export const WomanTshirt: string = "Woman T-shirt";
export const DreamBeautyFashion: string = "Dream Beauty Fashion";
export const WomensDress: string = "Womens's Dress";
export const Cyclamen: string = "Cyclamen";
export const ManTshirt: string = "Man's T-shirt";
export const Levis: string = "Levi's";
export const Diesel: string = "Diesel";
export const Lee: string = "Lee";
export const Hudson: string = "Hudson";
export const Denizen: string = "Denizen";
export const Spykar: string = "Spykar";
export const Colors: string = "Colors";
export const STEP: number = 10;
export const MIN: number = 10;
export const MAX: number = 1250;
export const NewProducts: string = "New Products";
export const ModalWomanText: string = "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Denim Jacket.";
export const ModalMensText: string = "Lorate Solid Men's Fashion Full Sleeves Latest Jacket for Men With Button Closure Long Sleeve Casual Torn Lycra Denim Jacket.";
export const ModalLongText: string = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.";
export const ModalRavaiyaaText: string = "Ravaiyaa - Attitude is everything Cotton Men's Dresses One Top Button T-Shirt.";
export const ModalRockText: string = "Rock Paper Scissors women's Tank Top High Neck Cotton Top Stylish Women Top..";
export const Quantity: string = "Quantity";
export const AddToCartButton: string = "Add to Cart";
export const ViewDetails: string = "View Details";

//Ecommerce - Invoices
export const BilledTo: string = "Billed To";
export const MofiMatchettVandelayGroupLTD: string = "Mofi Matchett Vandelay Group LTD";
export const UnitedStateTitleText: string = "2118 Thornridge Cir. Syracuse, Connecticut 35624, United State";
export const InvoiceDate: string = "Invoice Date";
export const InvoiceNumber: string = "Invoice Number";
export const AmountDus: string = "Amount Dus (USD)";
export const Rate: string = "Rate";
export const Qty: string = "Qty";
export const LineTotal: string = "Line Total";
export const AuthorizedSign: string = "Authorized Sign";
export const PrintInvoice: string = "Print Invoice";
export const Download: string = "Download";
export const Website: string = "Website";
export const InvoiceNo: string = "Invoice No.";
export const PaymentStatus: string = "Payment Status";
export const BillingDetails: string = "Billing Details";
export const TotalAmount: string = "Total Amount";
export const BillingAddress: string = "BILLING ADDRESS";
export const ShippingAddress: string = "SHIPPING ADDRESS";
export const Unit: string = "Unit";
export const Vat: string = "Vat %";
export const ShippingRate: string = "ShippingRate";
export const Invoice: string = "Invoice";
export const ClientDetails: string = "CLIENT DETAILS";
export const BankTransfer: string = "BANK TRANSFER";
export const BankAccount: string = "Bank Account";
export const TotalAmounts: string = "TOTAL AMOUNT";
export const AllTaxesIncluded: string = "All Taxes included";
export const Invoices: string = "INVOICE";
export const InvoiceTo: string = "Invoice to";
export const AccountNo: string = "Account No";
export const DueAmount: string = "Due Amount";
export const UnitePrice: string = "Unite Price";
export const PaymentTeams: string = "Payment Teams";
export const Tax: string = "Tax";
export const Discount: string = "Discount";
export const TotalDue: string = "Total Due";
export const No: string = "No.";
export const VATTax: string = "VAT / Tax 15%";
export const Mofi: string = "Mofi";
export const ItemDescription: string = "Item Description";
export const SubTotal: string = "Sub-total";
export const Subtotal: string = "Subtotal";
export const StateCountry = "State/Country"
export const TownCity = "Town/City"
export const PlaceOrder= "Place Order"
export const Products= "Product"
export const Total= "Total"
export const Shipping= "Shipping"
export const CashOnDelivery= "Cash On Delivery"
export const CheckPayments= "Check Payments"
export const ContactNo= "Contact No"

// ThemeCustomizer
export const CheckLayouts = "Check layouts";
export const QuickOption = "Quick option";
export const PreviewSettings = "PREVIEW SETTINGS";
export const Layout_Type = "Layout Type";
export const Sidebar_Icon = "Sidebar Icon";
export const UnlimitedColor = "Unlimited Color";
export const Mix_Layout = "MixLayout";
export const Sidebar_Type = 'Sidebar Type';
export const Box = "Box"
export const Fill= "Fill"
export const LTRBadges= "LTR"
export const RTLBadges = "RTL"
export const Stroke= "Stroke"
export const Configuration = 'Configuration';

//Ecommerce - Invoices
export const ProductForm = "Product Form"
export const ProductTitle ="Product Title"
export const DragFilesHere= "Drag files here"
export const AddTag = "Add Tag"
export const CreateNewCategoryHeading= "Create New Category"
export const CategoryName= "Category Name"
export const PublishStatus =" Publish Status"
export const PublishDateTime = "Publish Date & Time"
export const InitialCost= "Initial cost"
export const SellingPrice= "Selling price"
export const ChooseYourCurrency= "Choose your currency"
export  const ProductStocks = "Product stocks"
export const TypesOfProductDiscount = "Types of product discount"
export const AllowBackOrders= "Allow Backorders"
export const AdditionalTagTitle = "Additional Tag Title"
export const SpecificTags= "Specific Tags"
export const AdditionalDescription= "Additional Description"
export const WeightKg = "Weight (kg)"
export const Dimensions= "Dimensions"
export const ShippingClass= "Shipping Class"
export const Length= "Length[l]"
export const Width= "Width[w]"
export const Height= "Height[h]"
export const LowStock= "Low Stock"
export const PreOrder = "Pre-Order"
export const RestockDate = "Restock Date"
export const SKU= "SKU"
export const StockAvailability= "Stock Availability"
export const StockQuantity= "Stock Quantity"
export const MdeEditorText = `Enter your messages...`;
